data:
  data: QM9
  dir: './data'

ckpt: QM9

sampler:
  predictor: Reverse
  corrector: None #Langevin
  snr: 0.2
  scale_eps: 0.7
  n_steps: 1

sample:
  batch_size: 10000
  use_ema: False
  noise_removal: True
  probability_flow: False
  eps: 0.001
  seed: 42
