data:
  data: ZINC250k
  dir: './data'

ckpt: ZINC250k

sampler:
  predictor: Reverse
  corrector: Langevin
  snr: 0.2
  scale_eps: 0.7
  n_steps: 1

sample:
  batch_size: 2500
  use_ema: False
  noise_removal: True
  probability_flow: False
  eps: 0.001
  seed: 42
